let title = ['Getaran', 'Gelombang', 'Gelombang Longitudinal', 'Gelombang Mekanik', 'Gelombang Elektromagnetik', 'Propagasi Gelombang Tanah', 'Propagasi Gelombang Ionosfir', 'Propagasi Garis Pandang']

let pOne = ['Getaran merupakan gerakan bolak-balik suatu benda dalam selang waktu tertentu melalui titik      kesetimbangannya. Benda dikatakan bergetar dalam satu kali getaran penuh apabila benda bergerak dari titik awal dan kembali lagi ke titik awal tersebut.', 'Gelombang adalah suatu gangguan yang merambatkan energi dari satu titik ke titik lainnya. Gelombang juga dapat diartikan sebagai perambatan energi getaran dari satu titik ke titik lainnya. Gelombang dapat dibedakan berdasarkan medium perambatannya dan berdasarkan arah rambatnya. ', 'Berbeda dengan transverse wave, longitudinal merupakan gelombang yang arah getarannya sejajar atau berhimpit dengan arah rambatnya. Dalam satu gelombang longitudinal terdiri dari satu regangan dan satu rapatan. Perhitungan panjang satu gelombang longitudinal ini dinyatakan dalam satu rapatan dan regangan. Contohnya pada gelombang suara di udara.']

 let pTwo = ['Besaran-besaran fisika pada getaran yaitu periode (T), frekuensi (f), simpangan (x), dan amplitudo (A)', 'Gelombang pada contoh ini disebut gelombang transverse  atau transverse wave. Gelombang yang arah getarannya tegak lurus dengan arah rambatnya. Panjang satu gelombangnya dinyatakan dalam 1 bukit dan 1 lembah.' , 'Besaran-besaran fisika pada getaran yaitu periode (T), frekuensi (f), simpangan (x), amplitudo (A), panjang gelombang (λ), dan cepat rambat gelombang (v). Rumus cepat rambat gelombang: v = f x λ' ]

 let pThree = ['Gelombang juga dapat terbagi berdasarkan medium perambatannya, yaitu gelombang mekanik dan gelombang elektromagnetik.', 'Gelombang mekanik adalah Gelombang yang membutuhkan medium dalam perambatannya.', 'Contohnya adalah zat padat, zat cair, atau zat gas.', 'Gerakan pada gelombang laut disebabkan oleh angin yang berembus, sehingga membuat laut bergerak dan membentuk gelombang naik dan turun.']

 let pFour = ['Gelombang Elektromagnetik merupakan Gelombang yang tidak membutuhkan medium dalam perambatannya dan bisa merambat di ruang yang hampa udara.', 'Contohnya adalah cahaya matahari. Walaupun ruang angkasa adalah ruang yang hampa udara, tapi sinar matahari tetap bisa bersinar sampai ke bumi.', 'Jika kita melihat ke luar angkasa, tidak ada medium di sana. Tapi kita mendapatkan cahaya dari bintang-bintang yang jauh ini. Jadi cahaya atau gelombang radio dapat merambat melalui ketiadaan.']

 let pFive = ['Gelombang tanah (ground wave) adalah gelombang radio yang berpropagasi di sepanjang permukaan bumi/tanah.', ' Gelombang ini sering disebut dengan gelombang permukaan (surface wave)', 'Rugi-rugi (redaman) tanah akan meningkat dengan cepat dengan semakin besarnya frekuensi. Karena alasan tersebut, gelombang tanah sangat tidak efektif pada frekuensi di atas 2 MHz']

 let pSix = ['Pada frekuensi tinggi atau daerah HF, yang mempunyai range frekuensi 3 – 30 MHz, gelombang dapat dipropagasikan menempuh jarak yang jauh akibat dari pembiasan dan pemantulan lintasan pada lapisan ionospher.', 'Gelombang yang berpropagasi melalui lapisan ionosfir ini disebut sebagai gelombang ionosfir (ionospheric wave) atau juga disebut gelombang langit (sky wave).', 'Ionosfir tersusun dari 3 (tiga) lapisan, mulai dari yang terbawah yang disebut dengan lapisan D, E dan F. Sedangkan lapisan F dibagi menjadi dua, yaitu lapisan F1 dan F2 (yang lebih atas). ']

 let pSeven = ['Propagasi line of sight, disebut dengan propagasi dengan gelombang langsung (direct wave), karena gelombang yang terpancar dari antena pemancar langsung berpropagasi menuju antena penerima dan tidak merambat di atas permukaan tanah.', 'Band frekuensi yang digunakan pada jenis propagasi ini sangat lebar, yaitu meliputi band VHF (30 – 300 MHz), UHF (0,3 – 3 GHz), SHF (3 – 30 GHz) dan EHF (30 – 300 GHz), yang sering dikenal dengan band gelombang mikro (microwave).', 'Aplikasi untuk pelayanan komunikasi, antara lain : untuk siaran radio FM, sistem penyiaran televisi (TV), komunikasi bergerak, radar, komunikasi satelit, dan penelitian ruang angkasa']